/**
 * Greek letters, operators, relations, arrows, etc.
 * Expanded to align with common LaTeX symbol reference sheets (e.g. Rice / AMS-style tables).
 * Command name is without the leading backslash.
 */
export const SYMBOL_MAP: Readonly<Record<string, string>> = {
  // --- Lowercase Greek ---
  alpha: 'α',
  beta: 'β',
  gamma: 'γ',
  delta: 'δ',
  epsilon: 'ε',
  varepsilon: 'ϵ',
  zeta: 'ζ',
  eta: 'η',
  theta: 'θ',
  vartheta: 'ϑ',
  iota: 'ι',
  kappa: 'κ',
  varkappa: 'ϰ',
  lambda: 'λ',
  mu: 'μ',
  nu: 'ν',
  xi: 'ξ',
  pi: 'π',
  varpi: 'ϖ',
  rho: 'ρ',
  varrho: 'ϱ',
  sigma: 'σ',
  varsigma: 'ς',
  tau: 'τ',
  upsilon: 'υ',
  phi: 'ϕ',
  varphi: 'φ',
  chi: 'χ',
  psi: 'ψ',
  omega: 'ω',

  // --- Uppercase Greek ---
  Gamma: 'Γ',
  Delta: 'Δ',
  Theta: 'Θ',
  Lambda: 'Λ',
  Xi: 'Ξ',
  Pi: 'Π',
  Sigma: 'Σ',
  Upsilon: 'Υ',
  Phi: 'Φ',
  Psi: 'Ψ',
  Omega: 'Ω',

  // --- Hebrew (AMS) ---
  aleph: 'ℵ',
  beth: 'ℶ',
  gimel: 'ℷ',
  daleth: 'ℸ',

  // --- Binary operators ---
  pm: '±',
  mp: '∓',
  times: '×',
  div: '÷',
  ast: '∗',
  star: '⋆',
  circ: '∘',
  bullet: '∙',
  cdot: '·',
  cap: '∩',
  cup: '∪',
  uplus: '⊎',
  sqcap: '⊓',
  sqcup: '⊔',
  vee: '∨',
  wedge: '∧',
  setminus: '∖',
  wr: '≀',
  diamond: '⋄',
  bigtriangleup: '△',
  bigtriangledown: '▽',
  triangleleft: '◁',
  triangleright: '▷',
  lhd: '◁',
  rhd: '▷',
  unlhd: '⊴',
  unrhd: '⊵',
  oplus: '⊕',
  ominus: '⊖',
  otimes: '⊗',
  oslash: '⊘',
  odot: '⊙',
  bigcirc: '◯',
  dagger: '†',
  ddagger: '‡',
  amalg: '⨿',

  // --- Large operators (n-ary / integral family) ---
  sum: '∑',
  prod: '∏',
  coprod: '∐',
  int: '∫',
  oint: '∮',
  iint: '∬',
  iiint: '∭',
  bigcup: '⋃',
  bigcap: '⋂',
  biguplus: '⨄',
  bigvee: '⋁',
  bigwedge: '⋀',
  bigodot: '⨀',
  bigotimes: '⨂',
  bigoplus: '⨁',

  // --- Delimiters (Dirac / inner product) ---
  langle: '⟨',
  rangle: '⟩',

  // --- Calculus / differentials (common shorthands) ---
  partial: '∂',
  nabla: '∇',
  sqrt: '√',
  surd: '√',
  ell: 'ℓ',
  hbar: 'ℏ',

  // --- Relations ---
  leq: '≤',
  le: '≤',
  geq: '≥',
  ge: '≥',
  neq: '≠',
  ne: '≠',
  equiv: '≡',
  approx: '≈',
  simeq: '≃',
  sim: '∼',
  cong: '≅',
  propto: '∝',
  models: '⊧',
  vdash: '⊢',
  vDash: '⊨',
  Vvdash: '⊪',
  dashv: '⊣',
  mid: '∣',
  parallel: '∥',
  nparallel: '∦',
  perp: '⊥',
  bowtie: '⋈',
  Join: '⋈',
  smile: '⌣',
  frown: '⌢',
  asymp: '≍',
  doteq: '≐',
  ll: '≪',
  gg: '≫',
  prec: '≺',
  succ: '≻',
  preceq: '≼',
  succeq: '≽',
  curlyeqprec: '⋞',
  curlyeqsucc: '⋟',
  subset: '⊂',
  supset: '⊃',
  subseteq: '⊆',
  supseteq: '⊇',
  subsetneq: '⊊',
  supsetneq: '⊋',
  sqsubset: '⊏',
  sqsupset: '⊐',
  sqsubseteq: '⊑',
  sqsupseteq: '⊒',
  in: '∈',
  notin: '∉',
  ni: '∋',
  owns: '∋',

  // --- Negated relations (common) ---
  nless: '≮',
  ngtr: '≯',
  nleq: '≰',
  ngeq: '≱',
  nsubseteq: '⊈',
  nsupseteq: '⊉',
  nsim: '≁',
  nmid: '∤',
  nprec: '⊀',
  nsucc: '⊁',

  // --- Arrows ---
  to: '→',
  rightarrow: '→',
  leftarrow: '←',
  gets: '←',
  leftrightarrow: '↔',
  Rightarrow: '⇒',
  Leftarrow: '⇐',
  Leftrightarrow: '⇔',
  mapsto: '↦',
  hookleftarrow: '↩',
  hookrightarrow: '↪',
  nearrow: '↗',
  searrow: '↘',
  swarrow: '↙',
  nwarrow: '↖',
  uparrow: '↑',
  Uparrow: '⇑',
  downarrow: '↓',
  Downarrow: '⇓',
  updownarrow: '↕',
  Updownarrow: '⇕',
  longrightarrow: '⟶',
  longleftarrow: '⟵',
  longleftrightarrow: '⟷',
  Longrightarrow: '⟹',
  Longleftarrow: '⟸',
  Longleftrightarrow: '⟺',
  longmapsto: '⟼',
  rightleftharpoons: '⇌',
  leftrightharpoons: '⇋',
  rightrightarrows: '⇉',
  leftleftarrows: '⇇',
  curvearrowleft: '↶',
  curvearrowright: '↷',
  circlearrowleft: '↺',
  circlearrowright: '↻',

  // --- Infinity & empty ---
  infty: '∞',
  emptyset: '∅',
  varnothing: '∅',

  // --- Logic ---
  forall: '∀',
  exists: '∃',
  nexists: '∄',
  neg: '¬',
  lnot: '¬',
  land: '∧',
  lor: '∨',
  therefore: '∴',
  because: '∵',

  // --- Dots ---
  dots: '…',
  ldots: '…',
  cdots: '⋯',
  vdots: '⋮',
  ddots: '⋱',

  // --- Miscellaneous symbols ---
  top: '⊤',
  bot: '⊥',
  wp: '℘',
  Re: 'ℜ',
  Im: 'ℑ',
  mho: '℧',
  prime: '′',
  Prime: '″',
  degree: '°',
  angle: '∠',
  measuredangle: '∡',
  sphericalangle: '∢',
  triangle: '▵',
  backslash: '\\',

  // --- Currency / ordinals (text-like, often in math mode) ---
  S: '§',
  P: '¶',
};
